<?php

function OnlineSched_add_help_page() {
	$screen = get_current_screen();

	if ($screen->post_type == 'event_schedule' && $screen->taxonomy == '') {

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_general', 
			'title' => 'General Info',
			'content' => '<p>Event Scheduling is a tool for generating entries that can be used in a theme template file for events.  This is in early beta and more advanced help and future information will be provide as it is written.</p>',
		));

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_adding', 
			'title' => 'Adding Schedule',
			'content' => '<p>An Event is any activity which has a set of hours and a fixed location.</p>'.
				'<p>Field Description:<br/><ul>'.
				'<li>Title - Short description of the event</li>'.
				'<li>Body - Long description of the event.</li>'.
				'<li>Tag Type - Select as many categories as required.  New tags can be generated if you are an adminstrator.</li>'.
				'<li>Panelist Type - Select as many people as required.  New names can be generated by hitting "Add New Panelist Type."</li>'.
				'<li>Day of Week - Select the day in which the event will start. If you select "Unscheduled" it will not display on the website.</li>'.
				'<li>Start Time - Start time in military time with the minutes on the top and bottom of the hour.</li>'.
				'<li>Length - Length of event in minutes.</li>'.
				'<li>Room - Name of the room in which the primary entrance should be defined.</li></ul></p>'.
				'<p>Note: Please keep events within the physical day period.  As the system doesn\'t handle long multi-day events at this moment.</p>'
		));
	} else if ($screen->post_type == 'event_schedule' && $screen->taxonomy == 'event_schedule_room_type') {

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_general', 
			'title' => 'General Info',
			'content' => '<p>Room Type defines what rooms an event can be held in.</p>' .
				'<p>Field Description:<br/><ul>' .
				'<li>Name - What the room is called</li>' .
				'<li>Description - Used as sort order identifier</li>'.
				'<li>Slug - Not used (auto assigned if left blank)</li></ul></p>' .
				'<p>Note: As the system is designed there can be only one room assigned to an event. If multi-section rooms exists they should be addressed by the primary doorway that should be entered.</p>'
		));
	} else if ($screen->post_type == 'event_schedule' && $screen->taxonomy == 'event_schedule_tags_type') {

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_general', 
			'title' => 'General Info',
			'content' => '<p>Tag Type defines what descriptive searchings tags (or categories) applied to an event.</p>' .
				'<p>Field Description:<br/><ul>' .
				'<li>Name - Display term</li>' .
				'<li>Description - Not used</li>' .
				'<li>Slug - Not used (auto-assigned if left blank)</li>'.
				'<li>Parent - Not used</li></ul></p>' .
				'<p>Note: As the system is designed there can be only one room assigned to an event. If multi-section rooms exists they should be addressed by the primary doorway that should be entered.</p>'
		));
	} else if ($screen->post_type == 'event_schedule' && $screen->taxonomy == 'event_schedule_day_type') {

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_general', 
			'title' => 'General Info',
			'content' => '<p>Day Type defines the days in which the event will be held.</p>'.
				'<p>Field Description:<br/><ul>' .
				'<li>Name - Day of Week name</li>' .
				'<li>Description - Real date in MM/DD/YYYY format of the day</li>' .
				'<li>Slug - Not used (auto-assigned if left blank)</li>'.
				'<p>Note: If Description is 0 or an invalid date, the software will mark it as "unknown" in the interface.</p>'
		));
	} else if ($screen->post_type == 'event_schedule' && $screen->taxonomy == 'event_schedule_panelist_type') {

		$screen->add_help_tab(array(
			'id' => 'OnlineSched_general', 
			'title' => 'General Info',
			'content' => '<p>Panelist Type defines a list of panelists that can be selected to run the event.</p>'.
				'<p>Field Description:<br/><ul>' .
				'<li>Name - Person\'s Name on the panel</li>' .
				'<li>Description - Not used</li>' .
				'<li>Slug - Not used (auto-assigned if left blank)</li>'.
				'<li>Parent - Not used</li></ul></p>' .
				'<p>Note: Future versions will allow linking Panelists to Wordpress account, but currently this is the only data entry method.</p>'
		));
	} 
}

?>
