// @author kurst@mnfurs.org Kurst Hyperyote for Furry Migration
// Central selector map. Phase 9: Audited for theme decoupling.
//
// Plugin-owned selectors: Markup generated by OnlineSched.
// Theme-coupled selectors: Markup from host theme (e.g. FM theme) or user content.

const pluginSelectors = {
  // Page structure
  schedule:             '#schedule',
  scheduleItem:         '.schedule-item',
  scheduleDay:          '.schedule-day',
  scheduleHour:         '.schedule-hour',
  scheduleTitle:        '.schedule-title a',

  // Tabs
  tabList:              '.os-tabs',
  tabLinks:             '.os-tabs a',
  tabPaneActive:        '.os-tab-pane--active',
  tabProgramming:       '#programming',
  tabHours:             '#hours',

  // Filters
  searchInput:          '#schedule-search-text',
  selectTags:           '#schedule-select-tags',
  selectDays:           '#schedule-select-days',
  selectRooms:          '#schedule-select-rooms',
  resetButton:          '#schedule-reset',
  favoritesToggle:      '#schedule-favorites-toggle',

  // Favorites
  favoriteBtn:          '.schedule-favorite-toggle',

  // Modals
  loginModalBtn:        '#login-modal-btn',
  loginModal:           '#login-modal',
  loginModalClose:      '#login-modal-close',
  infoModalBtn:         '#info-modal-btn',
  infoModal:            '#info-modal',
  infoModalClose:       '#info-modal-close',
  scheduleModal:        '#modal-schedule',
  scheduleModalTitle:   '#modal-schedule-title',
  scheduleModalClose:   '#modal-schedule .os-close',
  androidModal:         '#android-google-calendar-modal',

  // Calendar
  modalIcal:            '#modal-schedule-ical',
  modalGoogle:          '#modal-schedule-google',
  modalCopyUrl:         '#modal-copy-url',
  clipboard:            '.schedule-clipboard',
  clipboardEffect:      '.os-clipboard-effect',

  // Buttons
  logoutBtn:            '#logout-modal-btn',

  // Responsive
  hiddenXs:             '.os-hide-mobile',
  visibleXs:            '.os-show-mobile',

  // Kiosk mode
  kioskClass:           '.kiosk-schedule',
  standardClass:        '.standard-schedule',
  addToCalendarSection: '#schedule-add-to-calendar',
  scheduleDescription:  '.schedule-description',
  scheduleIcalLink:     '.schedule-ical',
  scheduleGoogleLink:   '.schedule-google',
  tabMap:               '#map',
  hoursBlock:           '.os-hours',
  hoursRow:             '.os-hours__row',
  hoursDepartment:      '.os-hours__dept',
  hoursDay:             '.os-hours__days dt',
  hoursTimes:           '.os-hours__days dd',

  // Clickable inline filters (room/tag text in event rows)
  filterLink:           '.schedule-filter-link',
  scheduleRoom:         '.schedule-room',
  scheduleTags:         '.schedule-tags',

  // Badges
  badge:                '.os-badge',
  badgeDanger:          '.os-badge--danger',
  badgeSensory:         '.os-badge--sensory',
  badgeVip:             '.os-badge--vip',
  badgeEssentials:      '.os-badge--essentials',
  badgeCancelled:       '.os-badge--cancelled',
  badgeStreaming:        '.os-badge--streaming',
  badgeGoh:             '.os-badge--goh',
  badgeSpecialGuest:    '.os-badge--specialguest',
  badgeIcon:            '.os-badge--icon',
};

const themeSelectors = {
  // Furry Migration theme couplings
  footer:               '#footer',
  titleLeft:            '.title-left',
  titleRight:           '.title-right',
  footerMenu:           '.footer-menu',
  footerSocial:         '.footer-social',
  
  // User content couplings (markup inside WP post content)
  modalDescription:     '#modal-schedule-description',
};

module.exports = {
  ...pluginSelectors,
  ...themeSelectors,
  plugin: pluginSelectors,
  theme: themeSelectors,
};
